import {
  RentalListing,
  makeINR,
  makeMinutes,
  makeKilometers,
  makeFbPostId,
  ListingId,
} from '../../domain/types';

export const PROTOTYPE_LISTINGS: readonly RentalListing[] = [
  {
    id: 101 as ListingId,
    fbPostId: makeFbPostId('fb_proto_101'),
    groupName: 'Flat and Flatmates Bangalore (No Brokers)',
    groupNames: [
      'Flat and Flatmates Bangalore (No Brokers)',
      'Kadubeesanahalli & Bellandur Rentals',
      'Prestige Tech Park Flatmates',
    ],
    postCount: 3,
    postUrl: 'https://www.facebook.com/groups/flatandflatmates/posts/101',
    authorName: 'Aakash Verma',
    postedTime: '28m ago',
    title: 'Master Bedroom in 3BHK Gated Society • Kadubeesanahalli',
    summary: 'Spacious master bed with attached balcony & washroom in high-rise gated society. 8 mins walk to PTP back gate.',
    location: 'Kadubeesanahalli',
    landmark: 'Behind Prestige Tech Park Gate 1',
    bhkType: 'Private Room / Flatmate',
    imageUrls: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80',
    ],
    rawText: `1 Master Bedroom available in a luxury 3BHK at Prestige Tech Vista, Kadubeesanahalli.
Direct walking access to Prestige Tech Park (8 mins).
• Rent: ₹24,000 / month (includes maintenance)
• Deposit: ₹48,000 (strictly 2.0x rent multiple, no 10-month lock-in)
• Cauvery water 24/7 + borewell backup
• Full 100% DG power backup (WFH ready)
• Attached washroom with geyser & glass cubicle
• Swimming pool, gym, badminton court inside society
• Zero brokerage (Direct from current flatmates)
• Male bachelor friendly, non-veg allowed, chill environment
Contact: 9845019823 on WhatsApp.`,
    entities: {
      rent: makeINR(24000),
      deposit: makeINR(48000),
      isBrokerage: false,
      isGatedSociety: true,
      societyName: 'Prestige Tech Vista',
      landmark: 'Behind Prestige Tech Park Gate 1',
      hasSwimmingPool: true,
      hasPowerBackup: true,
      hasAttachedWashroom: true,
      hasBalcony: true,
      isVegetarianOnly: false,
      isMaleBachelorAllowed: true,
      isFemaleOnly: false,
      isWalkingDistance: true,
      furnishing: 'Fully Furnished',
      isKadubeesanahalliDirect: true,
      contactPhone: '9845019823',
    },
    commute: {
      distanceKm: makeKilometers(0.8),
      inboundMins: makeMinutes(8),
      outboundMins: makeMinutes(9),
      twoWayAvgPeakMins: makeMinutes(8),
      hasPanathurUnderpassBottleneck: false,
    },
    score: 96,
    scoreBreakdown: {
      base: 50,
      rent: 20,
      brokerage: 15,
      deposit: 10,
      gatedSociety: 15,
      swimmingPool: 15,
      powerBackup: 10,
      attachedWashroom: 10,
      vegetarianPenalty: 0,
      bachelorMatch: 10,
      walkProximity: 15,
      furnished: 5,
      panathurBypass: 10,
      commute: 20,
    },
    tier: '🔥 Unicorn Deal',
    userStatus: 'new',
    createdAt: '2026-10-07T18:00:00Z',
    updatedAt: '2026-10-07T18:00:00Z',
  },
  {
    id: 102 as ListingId,
    fbPostId: makeFbPostId('fb_proto_102'),
    groupName: 'Bellandur & Outer Ring Road Flatmates',
    groupNames: ['Bellandur & Outer Ring Road Flatmates'],
    postCount: 1,
    postUrl: 'https://www.facebook.com/groups/bellandurflatmates/posts/102',
    authorName: 'Sneha Kulkarni',
    postedTime: '1h ago',
    title: 'Spacious 2 BHK in Green Glen Layout • Bellandur',
    summary: 'Full 2BHK flat in premium standalone building with lift, security & Cauvery water. 14m scooter commute to PTP.',
    location: 'Bellandur',
    landmark: 'Green Glen Layout, Near Sobha Carnation',
    bhkType: '2 BHK (Shared/Full)',
    imageUrls: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&auto=format&fit=crop&q=80',
    ],
    rawText: `Full 2 BHK available for rent in Green Glen Layout, Bellandur.
• Rent: ₹38,000 / month
• Deposit: ₹1,00,000
• Kaveri water connection with overhead tank
• Semi-furnished with modular kitchen, wardrobes, TV unit
• 100% power backup for common areas and fans/lights
• 2 Balconies, excellent ventilation and sunlight
• Covered car & 2-wheeler parking
• Direct from owner, NO BROKERAGE
• 3.2 km to PTP / EcoSpace
Contact owner via WhatsApp: 9886023411.`,
    entities: {
      rent: makeINR(38000),
      deposit: makeINR(100000),
      isBrokerage: false,
      isGatedSociety: false,
      societyName: 'Green Glen Residency',
      landmark: 'Near Sobha Carnation',
      hasSwimmingPool: false,
      hasPowerBackup: true,
      hasAttachedWashroom: true,
      hasBalcony: true,
      isVegetarianOnly: false,
      isMaleBachelorAllowed: true,
      isFemaleOnly: false,
      isWalkingDistance: false,
      furnishing: 'Semi-Furnished',
      isKadubeesanahalliDirect: false,
      contactPhone: '9886023411',
    },
    commute: {
      distanceKm: makeKilometers(3.2),
      inboundMins: makeMinutes(13),
      outboundMins: makeMinutes(17),
      twoWayAvgPeakMins: makeMinutes(15),
      hasPanathurUnderpassBottleneck: false,
    },
    score: 84,
    scoreBreakdown: {
      base: 50,
      rent: 10,
      brokerage: 15,
      deposit: 0,
      gatedSociety: 0,
      swimmingPool: 0,
      powerBackup: 10,
      attachedWashroom: 10,
      vegetarianPenalty: 0,
      bachelorMatch: 10,
      walkProximity: 0,
      furnished: 5,
      panathurBypass: 10,
      commute: 15,
    },
    tier: '✨ Great Match',
    userStatus: 'new',
    createdAt: '2026-10-07T17:30:00Z',
    updatedAt: '2026-10-07T17:30:00Z',
  },
  {
    id: 103 as ListingId,
    fbPostId: makeFbPostId('fb_proto_103'),
    groupName: 'Bangalore Rentals & Flatmates (Tech Corridor)',
    groupNames: [
      'Bangalore Rentals & Flatmates (Tech Corridor)',
      'Panathur Balagere Flats',
    ],
    postCount: 2,
    postUrl: 'https://www.facebook.com/groups/bangalorerentals/posts/103',
    authorName: 'Vikram Joshi',
    postedTime: '2h ago',
    title: '1 BHK in Balagere / Panathur Road • Sobha Dream Acres',
    summary: 'Compact 1BHK in Sobha Dream Acres mega-township. Olympic pool, 5 clubhouses, but heavy Panathur railway underpass bottleneck.',
    location: 'Panathur',
    landmark: 'Sobha Dream Acres, Balagere',
    bhkType: '1 BHK',
    imageUrls: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&auto=format&fit=crop&q=80',
    ],
    rawText: `Cozy 1 BHK flat available in Sobha Dream Acres, Panathur / Balagere.
• Rent: ₹21,000 / month
• Maintenance: ₹2,800 / month (separate)
• Deposit: ₹60,000
• Fully gated society with Olympic swimming pool, gym, 5 clubhouses
• Tanker water + STP treated water (no Cauvery pipeline yet)
• Note on commute: Panathur railway underpass gets choked between 9:30-11:00 AM and 5:30-7:30 PM (+15 mins delay).
• Bachelor friendly, zero brokerage
Call or WhatsApp: 9741098120.`,
    entities: {
      rent: makeINR(21000),
      deposit: makeINR(60000),
      isBrokerage: false,
      isGatedSociety: true,
      societyName: 'Sobha Dream Acres',
      landmark: 'Balagere Main Road',
      hasSwimmingPool: true,
      hasPowerBackup: true,
      hasAttachedWashroom: true,
      hasBalcony: true,
      isVegetarianOnly: false,
      isMaleBachelorAllowed: true,
      isFemaleOnly: false,
      isWalkingDistance: false,
      furnishing: 'Semi-Furnished',
      isKadubeesanahalliDirect: false,
      contactPhone: '9741098120',
    },
    commute: {
      distanceKm: makeKilometers(4.6),
      inboundMins: makeMinutes(22),
      outboundMins: makeMinutes(31),
      twoWayAvgPeakMins: makeMinutes(26),
      hasPanathurUnderpassBottleneck: true,
    },
    score: 68,
    scoreBreakdown: {
      base: 50,
      rent: 20,
      brokerage: 15,
      deposit: 5,
      gatedSociety: 15,
      swimmingPool: 15,
      powerBackup: 10,
      attachedWashroom: 10,
      vegetarianPenalty: 0,
      bachelorMatch: 10,
      walkProximity: 0,
      furnished: 0,
      panathurBypass: -15,
      commute: -10,
    },
    tier: '⚡ Moderate Match',
    userStatus: 'new',
    createdAt: '2026-10-07T16:00:00Z',
    updatedAt: '2026-10-07T16:00:00Z',
  },
  {
    id: 104 as ListingId,
    fbPostId: makeFbPostId('fb_proto_104'),
    groupName: 'Cessna Business Park & Marathahalli Flatmates',
    groupNames: ['Cessna Business Park & Marathahalli Flatmates'],
    postCount: 1,
    postUrl: 'https://www.facebook.com/groups/cessnaflatmates/posts/104',
    authorName: 'Priya Sundaram',
    postedTime: '3h ago',
    title: '1 Room in 3BHK Gated Community • Marathahalli ORR',
    summary: 'Executive room with attached bath in Rohan Viti. 16 mins scooter ride to PTP. Cauvery water & power backup.',
    location: 'Marathahalli',
    landmark: 'Near Marathahalli Innovative Multiplex Bridge',
    bhkType: 'Private Room / Flatmate',
    imageUrls: [
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80',
    ],
    rawText: `Single private room in a 3BHK flat at Rohan Viti, Marathahalli ORR.
• Rent: ₹19,500 / month
• Deposit: ₹40,000 (about 2.0x rent)
• Cauvery water supply 24 hrs
• Power backup for entire flat
• Attached washroom with geyser
• Modular kitchen with chimney, fridge, washing machine setup
• Gated society with swimming pool and gym
• Brokerage applicable: 15 days brokerage fee
• Contact agent: 9900112233.`,
    entities: {
      rent: makeINR(19500),
      deposit: makeINR(40000),
      isBrokerage: true,
      isGatedSociety: true,
      societyName: 'Rohan Viti',
      landmark: 'Near Innovative Multiplex Bridge',
      hasSwimmingPool: true,
      hasPowerBackup: true,
      hasAttachedWashroom: true,
      hasBalcony: false,
      isVegetarianOnly: false,
      isMaleBachelorAllowed: true,
      isFemaleOnly: false,
      isWalkingDistance: false,
      furnishing: 'Fully Furnished',
      isKadubeesanahalliDirect: false,
      contactPhone: '9900112233',
    },
    commute: {
      distanceKm: makeKilometers(3.8),
      inboundMins: makeMinutes(15),
      outboundMins: makeMinutes(21),
      twoWayAvgPeakMins: makeMinutes(18),
      hasPanathurUnderpassBottleneck: false,
    },
    score: 72,
    scoreBreakdown: {
      base: 50,
      rent: 20,
      brokerage: -40,
      deposit: 10,
      gatedSociety: 15,
      swimmingPool: 15,
      powerBackup: 10,
      attachedWashroom: 10,
      vegetarianPenalty: 0,
      bachelorMatch: 10,
      walkProximity: 0,
      furnished: 5,
      panathurBypass: 10,
      commute: 10,
    },
    tier: '⚡ Moderate Match',
    userStatus: 'new',
    createdAt: '2026-10-07T15:00:00Z',
    updatedAt: '2026-10-07T15:00:00Z',
  },
  {
    id: 105 as ListingId,
    fbPostId: makeFbPostId('fb_proto_105'),
    groupName: 'Flat and Flatmates Bangalore (No Brokers)',
    groupNames: ['Flat and Flatmates Bangalore (No Brokers)'],
    postCount: 1,
    postUrl: 'https://www.facebook.com/groups/flatandflatmates/posts/105',
    authorName: 'Ramesh Reddy',
    postedTime: '4h ago',
    title: '1 BHK Standalone • Boganahalli / Cessna Tech Zone',
    summary: 'Spacious independent 1 BHK flat near Cessna Business Park. 10m commute to PTP, borewell water.',
    location: 'Cessna',
    landmark: 'Near Cessna Business Park Main Gate',
    bhkType: '1 BHK',
    imageUrls: [
      'https://images.unsplash.com/photo-1502005229762-ae1b460020e2?w=800&auto=format&fit=crop&q=80',
    ],
    rawText: `1 BHK independent flat in Boganahalli near Cessna Tech Park back road.
• Rent: ₹17,000 / month
• Deposit: ₹50,000
• Borewell water supply with continuous power
• Wardrobes, geyser, kitchen cabinets installed
• No lift, 2nd floor walk-up
• Pure veg only preferred
• No brokerage, direct owner
Phone: 9845567890.`,
    entities: {
      rent: makeINR(17000),
      deposit: makeINR(50000),
      isBrokerage: false,
      isGatedSociety: false,
      societyName: 'Reddy Nilaya',
      landmark: 'Near Cessna Business Park Main Gate',
      hasSwimmingPool: false,
      hasPowerBackup: false,
      hasAttachedWashroom: true,
      hasBalcony: true,
      isVegetarianOnly: true,
      isMaleBachelorAllowed: false,
      isFemaleOnly: false,
      isWalkingDistance: true,
      furnishing: 'Semi-Furnished',
      isKadubeesanahalliDirect: false,
      contactPhone: '9845567890',
    },
    commute: {
      distanceKm: makeKilometers(1.5),
      inboundMins: makeMinutes(10),
      outboundMins: makeMinutes(12),
      twoWayAvgPeakMins: makeMinutes(11),
      hasPanathurUnderpassBottleneck: false,
    },
    score: 42,
    scoreBreakdown: {
      base: 50,
      rent: 20,
      brokerage: 15,
      deposit: 5,
      gatedSociety: 0,
      swimmingPool: 0,
      powerBackup: 0,
      attachedWashroom: 10,
      vegetarianPenalty: -50,
      bachelorMatch: -25,
      walkProximity: 15,
      furnished: 0,
      panathurBypass: 10,
      commute: 20,
    },
    tier: '⚠️ Low Match',
    userStatus: 'new',
    createdAt: '2026-10-07T14:00:00Z',
    updatedAt: '2026-10-07T14:00:00Z',
  },
];
